name: Pelican Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Pelican Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: |
            ./.venv
          key: ${{ runner.os }}-${{ hashFiles('./poetry.lock') }}
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-suggests --no-install-recommends curl python3 jq

          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --with dev
      - name: Pelican Publish
        run: |
          poetry shell
          make github
