name: Pelican Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Pelican Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: |
            ./.venv
          key: ${{ runner.os }}-${{ hashFiles('./poetry.lock') }}
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --with dev
      - name: Pelican Publish
        run: |
          poetry run make github
